### PR TITLE
Feature/cli environment vars

### PR DESCRIPTION
**Pull request by morostr**

### CODE REVIEW

**Comment by morostr** [comment]
Vote for not fixing the last codeclimate error. It makes no sense to make that method shorter, and its only 26 lines.

**Comment by mgskjaeveland** [comment]
Looking closer at the codeclimate error and its surroundings have given me ideas for code improvements, e.g, there is a bit of overlap between the CLI and servlet. Let me have a stab at it. This also connects with #21.

**Comment by morostr** [comment]
are you stabbing in this branch? If not I think we should merge the PR first.

**Comment by mgskjaeveland** [comment]
Have disabled one CLI test, as I think it is not good to remove the original input extension to the output file. Suggest that we only add the output extension to the output. Note also that the CLI options have changed. Please review and merge at will.

**Comment by mgskjaeveland** [comment]
Also, I think that the code climate issue is a bit harsh, but will take a look.

**Pull request merged**
